# # This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# # This workflow uses actions that are not certified by GitHub.
# # They are provided by a third-party and are governed by
# # separate terms of service, privacy policy, and support
# # documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "build" ]
  pull_request:
    branches: [ "build" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Node.js (for create-dmg or utilities)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven


      - name: Build project w/ Maven
        run: mvn clean package
      # - name: Build project with Maven
      #   run:  ./mvnw clean package

      - name: Run Packr for windows
        run: |
          rm -r app/win/packr
          java -jar packr/packr-all-4.0.0.jar packr/packr-config_win.json

#      - name: Run Inno-Setup for windows
#        run: '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" inno-setup/installer.iss'
          

      - name: Run Packr for Mac
        run: |
          rm -r app/mac
          java -jar packr/packr-all-4.0.0.jar packr/packr-config_mac.json

#      - name: Wrap to .dmg for Mac
#        run: |
#          npm install -g create-dmg
#          npx create-dmg 'app/mac/MPR-Bio-Remote.app' \
#            --overwrite \
#            --dmg-title="MPR-Bio-Remote" \
#            --icon "MPR-Bio-Remote.app" 150 150 \
#            --window-size 500 300 \
#            --app-drop-link 350 150 \
#            dist/

# - name: Run Packr for Linux
      #   run: |
      #     rm -r app/lin
      #     java -jar packr/packr-all-4.0.0.jar packr/packr-config_lin.json

#      - name: Archive packaged app
#        uses: actions/upload-artifact@v4
#        with:
#          name: mpr-bio-remote
#          path: |
#            app/win/**
#            app/mac/**
#            app/lin/**
#            target/**
#
#    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#      - name: Update dependency graph
#        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
